FROM python:3.10

WORKDIR /code

COPY main.py /code/main.py
COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

CMD ["python", "main.py"]
